// export const countryCodes = {
//   US: { code: "+1", name: "United States", flag: "/country/us.png", rec: "US" },
//   UK: { code: "+44", name: "United Kingdom", flag: "/country/uk.png", rec: "UK" },
//   AU: { code: "+61", name: "Australia", flag: "/country/au.png", rec: "AU" },
// };

export const countryCodes = {
  US: { code: "+1", name: "United States", flag: "/country/us.png", rec: "US" },
  AF: { code: "+93", name: "Afghanistan", flag: "/country/af.png", rec: "AF" },
  AL: { code: "+355", name: "Albania", flag: "/country/al.png", rec: "AL" },
  DZ: { code: "+213", name: "Algeria", flag: "/country/dz.png", rec: "DZ" },
  AS: { code: "+1684", name: "American Samoa", flag: "/country/as.png", rec: "AS" },
  AD: { code: "+376", name: "Andorra", flag: "/country/ad.png", rec: "AD" },
  AO: { code: "+244", name: "Angola", flag: "/country/ao.png", rec: "AO" },
  AI: { code: "+1264", name: "Anguilla", flag: "/country/ai.png", rec: "AI" },
  AQ: { code: "+672", name: "Antarctica", flag: "/country/aq.png", rec: "AQ" },
  AG: {
    code: "+1268",
    name: "Antigua and Barbuda",
    flag: "/country/ag.png",
    rec: "AG",
  },
  AR: { code: "+54", name: "Argentina", flag: "/country/ar.png", rec: "AR" },
  AM: { code: "+374", name: "Armenia", flag: "/country/am.png", rec: "AM" },
  AW: { code: "+297", name: "Aruba", flag: "/country/aw.png", rec: "AW" },
  AU: { code: "+61", name: "Australia", flag: "/country/au.png", rec: "AU" },
  AT: { code: "+43", name: "Austria", flag: "/country/at.png", rec: "AT" },
  AZ: { code: "+994", name: "Azerbaijan", flag: "/country/az.png", rec: "AZ" },
  BS: { code: "+1242", name: "Bahamas", flag: "/country/bs.png", rec: "BS" },
  BH: { code: "+973", name: "Bahrain", flag: "/country/bh.png", rec: "BH" },
  BD: { code: "+880", name: "Bangladesh", flag: "/country/bd.png", rec: "BD" },
  BB: { code: "+1246", name: "Barbados", flag: "/country/bb.png", rec: "BB" },
  BY: { code: "+375", name: "Belarus", flag: "/country/by.png", rec: "BY" },
  BE: { code: "+32", name: "Belgium", flag: "/country/be.png", rec: "BE" },
  BZ: { code: "+501", name: "Belize", flag: "/country/bz.png", rec: "BZ" },
  BJ: { code: "+229", name: "Benin", flag: "/country/bj.png", rec: "BJ" },
  BM: { code: "+1441", name: "Bermuda", flag: "/country/bm.png", rec: "BM" },
  BT: { code: "+975", name: "Bhutan", flag: "/country/bt.png", rec: "BT" },
  BO: { code: "+591", name: "Bolivia", flag: "/country/bo.png", rec: "BO" },
  BA: {
    code: "+387",
    name: "Bosnia and Herzegovina",
    flag: "/country/ba.png",
    rec: "BA",
  },
  BW: { code: "+267", name: "Botswana", flag: "/country/bw.png", rec: "BW" },
  BV: { code: "+47", name: "Bouvet Island", flag: "/country/bv.png", rec: "BV" },
  BR: { code: "+55", name: "Brazil", flag: "/country/br.png", rec: "BR" },
  IO: {
    code: "+246",
    name: "British Indian Ocean Territory",
    flag: "/country/io.png",
    rec: "IO",
  },
  VG: {
    code: "+1284",
    name: "British Virgin Islands",
    flag: "/country/vg.png",
    rec: "VG",
  },
  BN: { code: "+673", name: "Brunei", flag: "/country/bn.png", rec: "BN" },
  BG: { code: "+359", name: "Bulgaria", flag: "/country/bg.png", rec: "BG" },
  BF: { code: "+226", name: "Burkina Faso", flag: "/country/bf.png", rec: "BF" },
  BI: { code: "+257", name: "Burundi", flag: "/country/bi.png", rec: "BI" },
  KH: { code: "+855", name: "Cambodia", flag: "/country/kh.png", rec: "KH" },
  CM: { code: "+237", name: "Cameroon", flag: "/country/cm.png", rec: "CM" },
  CA: { code: "+1", name: "Canada", flag: "/country/ca.png", rec: "CA" },
  CV: { code: "+238", name: "Cape Verde", flag: "/country/cv.png", rec: "CV" },
  KY: { code: "+1345", name: "Cayman Islands", flag: "/country/ky.png", rec: "KY" },
  CF: {
    code: "+236",
    name: "Central African Republic",
    flag: "/country/cf.png",
    rec: "CF",
  },
  TD: { code: "+235", name: "Chad", flag: "/country/td.png", rec: "TD" },
  CL: { code: "+56", name: "Chile", flag: "/country/cl.png", rec: "CL" },
  CN: { code: "+86", name: "China", flag: "/country/cn.png", rec: "CN" },
  CX: { code: "+61", name: "Christmas Island", flag: "/country/cx.png", rec: "CX" },
  CC: { code: "+61", name: "Cocos Islands", flag: "/country/cc.png", rec: "CC" },
  CO: { code: "+57", name: "Colombia", flag: "/country/co.png", rec: "CO" },
  KM: { code: "+269", name: "Comoros", flag: "/country/km.png", rec: "KM" },
  CK: { code: "+682", name: "Cook Islands", flag: "/country/ck.png", rec: "CK" },
  CR: { code: "+506", name: "Costa Rica", flag: "/country/cr.png", rec: "CR" },
  HR: { code: "+385", name: "Croatia", flag: "/country/hr.png", rec: "HR" },
  CU: { code: "+53", name: "Cuba", flag: "/country/cu.png", rec: "CU" },
  CW: { code: "+599", name: "Curaçao", flag: "/country/cw.png", rec: "CW" },
  CY: { code: "+357", name: "Cyprus", flag: "/country/cy.png", rec: "CY" },
  CZ: { code: "+420", name: "Czech Republic", flag: "/country/cz.png", rec: "CZ" },
  CD: {
    code: "+243",
    name: "Democratic Republic of the Congo",
    flag: "/country/cd.png",
    rec: "CD",
  },
  DK: { code: "+45", name: "Denmark", flag: "/country/dk.png", rec: "DK" },
  DJ: { code: "+253", name: "Djibouti", flag: "/country/dj.png", rec: "DJ" },
  DM: { code: "+1767", name: "Dominica", flag: "/country/dm.png", rec: "DM" },
  DO: {
    code: "+1809, +1829, +1849",
    name: "Dominican Republic",
    flag: "/country/do.png",
    rec: "DO",
  },
  TL: { code: "+670", name: "East Timor", flag: "/country/tl.png", rec: "TL" },
  EC: { code: "+593", name: "Ecuador", flag: "/country/ec.png", rec: "EC" },
  EG: { code: "+20", name: "Egypt", flag: "/country/eg.png", rec: "EG" },
  SV: { code: "+503", name: "El Salvador", flag: "/country/sv.png", rec: "SV" },
  GQ: { code: "+240", name: "Equatorial Guinea", flag: "/country/gq.png", rec: "GQ" },
  ER: { code: "+291", name: "Eritrea", flag: "/country/er.png", rec: "ER" },
  EE: { code: "+372", name: "Estonia", flag: "/country/ee.png", rec: "EE" },
  ET: { code: "+251", name: "Ethiopia", flag: "/country/et.png", rec: "ET" },
  FK: { code: "+500", name: "Falkland Islands", flag: "/country/fk.png", rec: "FK" },
  FO: { code: "+298", name: "Faroe Islands", flag: "/country/fo.png", rec: "FO" },
  FJ: { code: "+679", name: "Fiji", flag: "/country/fj.png", rec: "FJ" },
  FI: { code: "+358", name: "Finland", flag: "/country/fi.png", rec: "FI" },
  FR: { code: "+33", name: "France", flag: "/country/fr.png", rec: "FR" },
  GF: { code: "+594", name: "French Guiana", flag: "/country/gf.png", rec: "GF" },
  PF: { code: "+689", name: "French Polynesia", flag: "/country/pf.png", rec: "PF" },
  TF: {
    code: "+262",
    name: "French Southern Territories",
    flag: "/country/tf.png",
    rec: "TF",
  },
  GA: { code: "+241", name: "Gabon", flag: "/country/ga.png", rec: "GA" },
  GM: { code: "+220", name: "Gambia", flag: "/country/gm.png", rec: "GM" },
  GE: { code: "+995", name: "Georgia", flag: "/country/ge.png", rec: "GE" },
  DE: { code: "+49", name: "Germany", flag: "/country/de.png", rec: "DE" },
  GH: { code: "+233", name: "Ghana", flag: "/country/gh.png", rec: "GH" },
  GI: { code: "+350", name: "Gibraltar", flag: "/country/gi.png", rec: "GI" },
  GR: { code: "+30", name: "Greece", flag: "/country/gr.png", rec: "GR" },
  GL: { code: "+299", name: "Greenland", flag: "/country/gl.png", rec: "GL" },
  GD: { code: "+1473", name: "Grenada", flag: "/country/gd.png", rec: "GD" },
  GP: { code: "+590", name: "Guadeloupe", flag: "/country/gp.png", rec: "GP" },
  GU: { code: "+1671", name: "Guam", flag: "/country/gu.png", rec: "GU" },
  GT: { code: "+502", name: "Guatemala", flag: "/country/gt.png", rec: "GT" },
  GG: { code: "+441481", name: "Guernsey", flag: "/country/gg.png", rec: "GG" },
  GN: { code: "+224", name: "Guinea", flag: "/country/gn.png", rec: "GN" },
  GW: { code: "+245", name: "GuineaBissau", flag: "/country/gw.png", rec: "GW" },
  GY: { code: "+592", name: "Guyana", flag: "/country/gy.png", rec: "GY" },
  HT: { code: "+509", name: "Haiti", flag: "/country/ht.png", rec: "HT" },
  HM: {
    code: "+672",
    name: "Heard Island and McDonald Islands",
    flag: "/country/hm.png",
    rec: "HM",
  },
  HN: { code: "+504", name: "Honduras", flag: "/country/hn.png", rec: "HN" },
  HK: { code: "+852", name: "Hong Kong", flag: "/country/hk.png", rec: "HK" },
  HU: { code: "+36", name: "Hungary", flag: "/country/hu.png", rec: "HU" },
  IS: { code: "+354", name: "Iceland", flag: "/country/is.png", rec: "IS" },
  IN: { code: "+91", name: "India", flag: "/country/in.png", rec: "IN" },
  ID: { code: "+62", name: "Indonesia", flag: "/country/id.png", rec: "ID" },
  IR: { code: "+98", name: "Iran", flag: "/country/ir.png", rec: "IR" },
  IE: { code: "+353", name: "Ireland", flag: "/country/ie.png", rec: "IE" },
  IM: { code: "+441624", name: "Isle of Man", flag: "/country/im.png", rec: "IM" },
  IL: { code: "+972", name: "Israel", flag: "/country/il.png", rec: "IL" },
  IT: { code: "+39", name: "Italy", flag: "/country/it.png", rec: "IT" },
  CI: { code: "+225", name: "Ivory Coast", flag: "/country/ci.png", rec: "CI" },
  JM: { code: "+1876", name: "Jamaica", flag: "/country/jm.png", rec: "JM" },
  JP: { code: "+81", name: "Japan", flag: "/country/jp.png", rec: "JP" },
  JE: { code: "+441534", name: "Jersey", flag: "/country/je.png", rec: "JE" },
  JO: { code: "+962", name: "Jordan", flag: "/country/jo.png", rec: "JO" },
  KZ: { code: "+7", name: "Kazakhstan", flag: "/country/kz.png", rec: "KZ" },
  KE: { code: "+254", name: "Kenya", flag: "/country/ke.png", rec: "KE" },
  KI: { code: "+686", name: "Kiribati", flag: "/country/ki.png", rec: "KI" },
  XK: { code: "+383", name: "Kosovo", flag: "/country/xk.png", rec: "XK" },
  KW: { code: "+965", name: "Kuwait", flag: "/country/kw.png", rec: "KW" },
  KG: { code: "+996", name: "Kyrgyzstan", flag: "/country/kg.png", rec: "KG" },
  LA: { code: "+856", name: "Laos", flag: "/country/la.png", rec: "LA" },
  LV: { code: "+371", name: "Latvia", flag: "/country/lv.png", rec: "LV" },
  LB: { code: "+961", name: "Lebanon", flag: "/country/lb.png", rec: "LB" },
  LS: { code: "+266", name: "Lesotho", flag: "/country/ls.png", rec: "LS" },
  LR: { code: "+231", name: "Liberia", flag: "/country/lr.png", rec: "LR" },
  LY: { code: "+218", name: "Libya", flag: "/country/ly.png", rec: "LY" },
  LI: { code: "+423", name: "Liechtenstein", flag: "/country/li.png", rec: "LI" },
  LT: { code: "+370", name: "Lithuania", flag: "/country/lt.png", rec: "LT" },
  LU: { code: "+352", name: "Luxembourg", flag: "/country/lu.png", rec: "LU" },
  MO: { code: "+853", name: "Macao", flag: "/country/mo.png", rec: "MO" },
  MK: { code: "+389", name: "Macedonia", flag: "/country/mk.png", rec: "MK" },
  MG: { code: "+261", name: "Madagascar", flag: "/country/mg.png", rec: "MG" },
  MW: { code: "+265", name: "Malawi", flag: "/country/mw.png", rec: "MW" },
  MY: { code: "+60", name: "Malaysia", flag: "/country/my.png", rec: "MY" },
  MV: { code: "+960", name: "Maldives", flag: "/country/mv.png", rec: "MV" },
  ML: { code: "+223", name: "Mali", flag: "/country/ml.png", rec: "ML" },
  MT: { code: "+356", name: "Malta", flag: "/country/mt.png", rec: "MT" },
  MH: { code: "+692", name: "Marshall Islands", flag: "/country/mh.png", rec: "MH" },
  MQ: { code: "+596", name: "Martinique", flag: "/country/mq.png", rec: "MQ" },
  MR: { code: "+222", name: "Mauritania", flag: "/country/mr.png", rec: "MR" },
  MU: { code: "+230", name: "Mauritius", flag: "/country/mu.png", rec: "MU" },
  YT: { code: "+262", name: "Mayotte", flag: "/country/yt.png", rec: "YT" },
  MX: { code: "+52", name: "Mexico", flag: "/country/mx.png", rec: "MX" },
  FM: { code: "+691", name: "Micronesia", flag: "/country/fm.png", rec: "FM" },
  MD: { code: "+373", name: "Moldova", flag: "/country/md.png", rec: "MD" },
  MC: { code: "+377", name: "Monaco", flag: "/country/mc.png", rec: "MC" },
  MN: { code: "+976", name: "Mongolia", flag: "/country/mn.png", rec: "MN" },
  ME: { code: "+382", name: "Montenegro", flag: "/country/me.png", rec: "ME" },
  MS: { code: "+1664", name: "Montserrat", flag: "/country/ms.png", rec: "MS" },
  MA: { code: "+212", name: "Morocco", flag: "/country/ma.png", rec: "MA" },
  MZ: { code: "+258", name: "Mozambique", flag: "/country/mz.png", rec: "MZ" },
  MM: { code: "+95", name: "Myanmar", flag: "/country/mm.png", rec: "MM" },
  NA: { code: "+264", name: "Namibia", flag: "/country/na.png", rec: "NA" },
  NR: { code: "+674", name: "Nauru", flag: "/country/nr.png", rec: "NR" },
  NP: { code: "+977", name: "Nepal", flag: "/country/np.png", rec: "NP" },
  NL: { code: "+31", name: "Netherlands", flag: "/country/nl.png", rec: "NL" },
  AN: {
    code: "+599",
    name: "Netherlands Antilles",
    flag: "/country/an.png",
    rec: "AN",
  },
  NZ: { code: "+64", name: "New Zealand", flag: "/country/nz.png", rec: "NZ" },
  NI: { code: "+505", name: "Nicaragua", flag: "/country/ni.png", rec: "NI" },
  NE: { code: "+227", name: "Niger", flag: "/country/ne.png", rec: "NE" },
  NG: { code: "+234", name: "Nigeria", flag: "/country/ng.png", rec: "NG" },
  NU: { code: "+683", name: "Niue", flag: "/country/nu.png", rec: "NU" },
  NF: { code: "+672", name: "Norfolk Island", flag: "/country/nf.png", rec: "NF" },
  KP: { code: "+850", name: "North Korea", flag: "/country/kp.png", rec: "KP" },
  MP: {
    code: "+1670",
    name: "Northern Mariana Islands",
    flag: "/country/mp.png",
    rec: "MP",
  },
  NO: { code: "+47", name: "Norway", flag: "/country/no.png", rec: "NO" },
  OM: { code: "+968", name: "Oman", flag: "/country/om.png", rec: "OM" },
  PK: { code: "+92", name: "Pakistan", flag: "/country/pk.png", rec: "PK" },
  PW: { code: "+680", name: "Palau", flag: "/country/pw.png", rec: "PW" },
  PS: {
    code: "+970",
    name: "Palestinian Territory",
    flag: "/country/ps.png",
    rec: "PS",
  },
  PA: { code: "+507", name: "Panama", flag: "/country/pa.png", rec: "PA" },
  PG: { code: "+675", name: "Papua New Guinea", flag: "/country/pg.png", rec: "PG" },
  PY: { code: "+595", name: "Paraguay", flag: "/country/py.png", rec: "PY" },
  PE: { code: "+51", name: "Peru", flag: "/country/pe.png", rec: "PE" },
  PH: { code: "+63", name: "Philippines", flag: "/country/ph.png", rec: "PH" },
  PN: { code: "+64", name: "Pitcairn", flag: "/country/pn.png", rec: "PN" },
  PL: { code: "+48", name: "Poland", flag: "/country/pl.png", rec: "PL" },
  PT: { code: "+351", name: "Portugal", flag: "/country/pt.png", rec: "PT" },
  PR: {
    code: "+1787, +1939",
    name: "Puerto Rico",
    flag: "/country/pr.png",
    rec: "PR",
  },
  QA: { code: "+974", name: "Qatar", flag: "/country/qa.png", rec: "QA" },
  CG: {
    code: "+242",
    name: "Republic of the Congo",
    flag: "/country/cg.png",
    rec: "CG",
  },
  RE: { code: "+262", name: "Réunion", flag: "/country/re.png", rec: "RE" },
  RO: { code: "+40", name: "Romania", flag: "/country/ro.png", rec: "RO" },
  RU: { code: "+7", name: "Russia", flag: "/country/ru.png", rec: "RU" },
  RW: { code: "+250", name: "Rwanda", flag: "/country/rw.png", rec: "RW" },
  BL: { code: "+590", name: "Saint Barthélemy", flag: "/country/bl.png", rec: "BL" },
  SH: { code: "+290", name: "Saint Helena", flag: "/country/sh.png", rec: "SH" },
  KN: {
    code: "+1869",
    name: "Saint Kitts and Nevis",
    flag: "/country/kn.png",
    rec: "KN",
  },
  LC: { code: "+1758", name: "Saint Lucia", flag: "/country/lc.png", rec: "LC" },
  MF: { code: "+590", name: "Saint Martin", flag: "/country/mf.png", rec: "MF" },
  PM: {
    code: "+508",
    name: "Saint Pierre and Miquelon",
    flag: "/country/pm.png",
    rec: "PM",
  },
  VC: {
    code: "+1784",
    name: "Saint Vincent and the Grenadines",
    flag: "/country/vc.png",
    rec: "VC",
  },
  WS: { code: "+685", name: "Samoa", flag: "/country/ws.png", rec: "WS" },
  SM: { code: "+378", name: "San Marino", flag: "/country/sm.png", rec: "SM" },
  ST: {
    code: "+239",
    name: "São Tomé and Príncipe",
    flag: "/country/st.png",
    rec: "ST",
  },
  SA: { code: "+966", name: "Saudi Arabia", flag: "/country/sa.png", rec: "SA" },
  SN: { code: "+221", name: "Senegal", flag: "/country/sn.png", rec: "SN" },
  RS: { code: "+381", name: "Serbia", flag: "/country/rs.png", rec: "RS" },
  SC: { code: "+248", name: "Seychelles", flag: "/country/sc.png", rec: "SC" },
  SL: { code: "+232", name: "Sierra Leone", flag: "/country/sl.png", rec: "SL" },
  SG: { code: "+65", name: "Singapore", flag: "/country/sg.png", rec: "SG" },
  SX: { code: "+1721", name: "Sint Maarten", flag: "/country/sx.png", rec: "SX" },
  SK: { code: "+421", name: "Slovakia", flag: "/country/sk.png", rec: "SK" },
  SI: { code: "+386", name: "Slovenia", flag: "/country/si.png", rec: "SI" },
  SB: { code: "+677", name: "Solomon Islands", flag: "/country/sb.png", rec: "SB" },
  SO: { code: "+252", name: "Somalia", flag: "/country/so.png", rec: "SO" },
  ZA: { code: "+27", name: "South Africa", flag: "/country/za.png", rec: "ZA" },
  GS: {
    code: "+500",
    name: "South Georgia and the South Sandwich Islands",
    flag: "/country/gs.png",
    rec: "GS",
  },
  KR: { code: "+82", name: "South Korea", flag: "/country/kr.png", rec: "KR" },
  SS: { code: "+211", name: "South Sudan", flag: "/country/ss.png", rec: "SS" },
  ES: { code: "+34", name: "Spain", flag: "/country/es.png", rec: "ES" },
  LK: { code: "+94", name: "Sri Lanka", flag: "/country/lk.png", rec: "LK" },
  SD: { code: "+249", name: "Sudan", flag: "/country/sd.png", rec: "SD" },
  SR: { code: "+597", name: "Suriname", flag: "/country/sr.png", rec: "SR" },
  SJ: {
    code: "+47",
    name: "Svalbard and Jan Mayen",
    flag: "/country/sj.png",
    rec: "SJ",
  },
  SZ: { code: "+268", name: "Swaziland", flag: "/country/sz.png", rec: "SZ" },
  SE: { code: "+46", name: "Sweden", flag: "/country/se.png", rec: "SE" },
  CH: { code: "+41", name: "Switzerland", flag: "/country/ch.png", rec: "CH" },
  SY: { code: "+963", name: "Syria", flag: "/country/sy.png", rec: "SY" },
  TW: { code: "+886", name: "Taiwan", flag: "/country/tw.png", rec: "TW" },
  TJ: { code: "+992", name: "Tajikistan", flag: "/country/tj.png", rec: "TJ" },
  TZ: { code: "+255", name: "Tanzania", flag: "/country/tz.png", rec: "TZ" },
  TH: { code: "+66", name: "Thailand", flag: "/country/th.png", rec: "TH" },
  TG: { code: "+228", name: "Togo", flag: "/country/tg.png", rec: "TG" },
  TK: { code: "+690", name: "Tokelau", flag: "/country/tk.png", rec: "TK" },
  TO: { code: "+676", name: "Tonga", flag: "/country/to.png", rec: "TO" },
  TT: {
    code: "+1868",
    name: "Trinidad and Tobago",
    flag: "/country/tt.png",
    rec: "TT",
  },
  TN: { code: "+216", name: "Tunisia", flag: "/country/tn.png", rec: "TN" },
  TR: { code: "+90", name: "Turkey", flag: "/country/tr.png", rec: "TR" },
  TM: { code: "+993", name: "Turkmenistan", flag: "/country/tm.png", rec: "TM" },
  TC: {
    code: "+1649",
    name: "Turks and Caicos Islands",
    flag: "/country/tc.png",
    rec: "TC",
  },
  TV: { code: "+688", name: "Tuvalu", flag: "/country/tv.png", rec: "TV" },
  VI: {
    code: "+1340",
    name: "U.S. Virgin Islands",
    flag: "/country/vi.png",
    rec: "VI",
  },
  UG: { code: "+256", name: "Uganda", flag: "/country/ug.png", rec: "UG" },
  UA: { code: "+380", name: "Ukraine", flag: "/country/ua.png", rec: "UA" },
  UAE: {
    code: "+971",
    name: "United Arab Emirates",
    flag: "/country/ae.png",
    rec: "AE",
  },
  Uk: { code: "+44", name: "United Kingdom", flag: "/country/gb.png", rec: "GB" },
  UY: { code: "+598", name: "Uruguay", flag: "/country/uy.png", rec: "UY" },
  UZ: { code: "+998", name: "Uzbekistan", flag: "/country/uz.png", rec: "UZ" },
  VU: { code: "+678", name: "Vanuatu", flag: "/country/vu.png", rec: "VU" },
  VA: { code: "+379", name: "Vatican", flag: "/country/va.png", rec: "VA" },
  VE: { code: "+58", name: "Venezuela", flag: "/country/ve.png", rec: "VE" },
  VN: { code: "+84", name: "Vietnam", flag: "/country/vn.png", rec: "VN" },
  WF: { code: "+681", name: "Wallis and Futuna", flag: "/country/wf.png", rec: "WF" },
  EH: { code: "+212", name: "Western Sahara", flag: "/country/eh.png", rec: "EH" },
  YE: { code: "+967", name: "Yemen", flag: "/country/ye.png", rec: "YE" },
  ZW: { code: "+263", name: "Zimbabwe", flag: "/country/zw.png", rec: "ZW" },
};
